SET(galilei_engines_INST_INCLUDES
	gdocranking.h
	gdocretrieved.h
	gengine.h
	gmetaengine.h
	gsugs.h
	gcomputesugs.h
	gcomputetrust.h
)

SET(galilei_engines_TARGET_SOURCES
	gdocranking.cpp
	gdocretrieved.cpp
	gengine.cpp
	gmetaengine.cpp
	gsugs.cpp
	gcomputesugs.cpp
	gcomputetrust.cpp
)