SET(galilei_engines_INST_INCLUDES
	gdocref.h
	gdocfragment.h
	gdocfragmentrank.h
	gdocfragmentranks.h
	gengine.h
	gmetaengine.h
	gsugs.h
	gcomputesugs.h
	gcomputetrust.h
	gcomputerank.h
)

SET(galilei_engines_TARGET_SOURCES
	gdocref.cpp
	gdocfragment.cpp
	gdocfragmentrank.cpp
	gdocfragmentranks.cpp
	gengine.cpp
	gmetaengine.cpp
	gsugs.cpp
	gcomputesugs.cpp
	gcomputetrust.cpp
	gcomputerank.cpp
)