IF(KDE4_FOUND)
    SET(sgga_docs_AVAILABLE_FRONTENDS kde)
    SET(sgga_docs_kde_DEPENDENCY rcorekde ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(sgga_docs_frontend sgga_docs kde sgga_docs_INCLUDES)
ENDIF(KDE4_FOUND)
