IF(QT4_FOUND)
    SET(sgga_docs_AVAILABLE_FRONTENDS qt)
    SET(sgga_docs_qt_DEPENDENCY rcoreqt ${QT_LIBRARIES})
    ADD_FRONTEND_SOURCE_FILE(sgga_docs_frontend sgga_docs qt sgga_docs_INCLUDES)
ENDIF(QT4_FOUND)
