IF(KDE4_FOUND)
    SET(statsims_AVAILABLE_FRONTENDS kde)
    SET(statsims_kde_DEPENDENCY rcorekde ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(statsims_frontend statsims kde statsims_INCLUDES)
ENDIF(KDE4_FOUND)
