SET(galilei_sessions_INST_INCLUDES
    gbasicsession.h
    gsession.h
    ggalileiprg.h
    galilei.h
    gstorage.h
    gslot.h
    gslotlog.h
    gplugin.h
    gstatscalc.h
    gsignalhandler.h
    gmeasure.h
    ggalileiapp.h
    gdebugobject.h
    gpluginmanager.h
    gpluginmanager.hh
    gplugin.hh
)


SET(galilei_sessions_TARGET_SOURCES
    gbasicsession.cpp
    gsession.cpp
    ggalileiprg.cpp
    gslot.cpp
    gslotlog.cpp
    gstorage.cpp
    gstatscalc.cpp
    gplugin.hh
    gpluginmanager.cpp
    gsignalhandler.cpp
    galilei.cpp
    gmeasure.cpp
    ggalileiapp.cpp
    gdebugobject.cpp
)