SET(galilei_sessions_INST_INCLUDES
    galilei.h
	gobject.h
	gobjects.h 
	gobjects.hh
	gobjectslist.h 
	gobjectslist.hh	
    gsession.h
    gsession.hh
    gbasicsession.h
    ggalileiprg.h    
    gstorage.h
    gslot.h
    gslotlog.h    
    ggalileiapp.h
    gsimulator.h
)


SET(galilei_sessions_TARGET_SOURCES
	galilei.cpp
	gobject.cpp       	
    gslot.cpp
    gslotlog.cpp
    gstorage.cpp          
    gsession.cpp
    ggalileiprg.cpp
    ggalileiapp.cpp
    gsimulator.cpp
)