MACRO(DO_GALILEI_R_LIB_INCLUDE _libPath)
        INCLUDE_DIRECTORIES("${_libPath}/galilei")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/docs")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/engines")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/frontend")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/frontend/kde")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/groups")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/historic")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/knowledge")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/profiles")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/sessions")
        INCLUDE_DIRECTORIES("${_libPath}/galilei/tools")
	    INCLUDE_DIRECTORIES("${_libPath}/build")
        
        LINK_DIRECTORIES(${_libPath}/build/galilei ${_libPath}/build/lib)
ENDMACRO(DO_GALILEI_R_LIB_INCLUDE)
