IF(KDE4_FOUND)
    SET(feedback_AVAILABLE_FRONTENDS kde)
    SET(feedback_kde_DEPENDENCY rcoreqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(feedback_frontend feedback kde feedback_INCLUDES)
ENDIF(KDE4_FOUND)
