IF(KDE3_FOUND)
    SET(feedback_AVAILABLE_FRONTENDS kde)
    SET(feedback_kde_DEPENDENCY rcorekde ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(feedback_frontend feedback kde feedback_INCLUDES)
ENDIF(KDE3_FOUND)
