IF(KDE4_FOUND)
    SET(subslevel_AVAILABLE_FRONTENDS kde)
    SET(subslevel_kde_DEPENDENCY rcoreqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(subslevel_frontend subslevel kde subslevel_INCLUDES)
ENDIF(KDE4_FOUND)
