IF(KDE4_FOUND)
    SET(gca_docs_AVAILABLE_FRONTENDS kde)
    SET(gca_docs_kde_DEPENDENCY rcorekde ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(gca_docs_frontend gca_docs kde gca_docs_INCLUDES)
ENDIF(KDE4_FOUND)
