IF(KDE3_FOUND)
    SET(gca_profiles_AVAILABLE_FRONTENDS kde)
    SET(gca_profiles_kde_DEPENDENCY rcorekde ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(gca_profiles_frontend gca_profiles kde gca_profiles_INCLUDES)
ENDIF(KDE3_FOUND)
