SET(galilei_knowledge_INST_INCLUDES
    gconceptcat.h
    gconcepttype.h
    gconcept.h
    gconceptlist.h
    gstatement.h
    gpredicate.h
    glang.h
    gkb.h
    gconceptref.h
    gvector.h
    gdescription.h
    gconcepttree.h
    gclass.h
    gclasses.h
    gdescriptionobject.h
    gdescriptionobject.hh
	 gobjectindex.h
)


SET(galilei_knowledge_TARGET_SOURCES
	 gconceptcat.cpp
    gconcepttype.cpp
    gconcept.cpp
    gconceptlist.cpp
    gstatement.cpp
    gpredicate.cpp
    gkb.cpp
    glang.cpp
    gconceptref.cpp
    gvector.cpp
    gdescription.cpp
    gconcepttree.cpp
    gclass.cpp
    gclasses.cpp
	 gobjectindex.cpp
)