IF(KDE4_FOUND)
    SET(thesaurus_AVAILABLE_FRONTENDS kde)
    SET(thesaurus_kde_DEPENDENCY rcoreqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(thesaurus_frontend thesaurus kde thesaurus_INCLUDES)
ENDIF(KDE4_FOUND)
