IF(KDE4_FOUND)
    SET(docsagree_AVAILABLE_FRONTENDS kde)
    SET(docsagree_kde_DEPENDENCY rcoreqt galileiqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(docsagree_frontend docsagree kde docsagree_INCLUDES)
ENDIF(KDE4_FOUND)
