IF(KDE4_FOUND)
    SET(docsgroupssims_AVAILABLE_FRONTENDS kde)
    SET(docsgroupssims_kde_DEPENDENCY rcoreqt galileiqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(docsgroupssims_frontend docsgroupssims kde docsgroupssims_INCLUDES)
ENDIF(KDE4_FOUND)
