IF(KDE4_FOUND)
    SET(docssims_AVAILABLE_FRONTENDS kde)
    SET(docssims_kde_DEPENDENCY rcorekde galileikde ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(docssims_frontend docssims kde docssims_INCLUDES)
ENDIF(KDE4_FOUND)
