IF(QT4_FOUND)
    SET(kmeans_docs_AVAILABLE_FRONTENDS qt)
    SET(kmeans_docs_qt_DEPENDENCY rcoreqt ${QT_LIBRARIES})
    ADD_FRONTEND_SOURCE_FILE(kmeans_docs_frontend kmeans_docs qt kmeans_docs_INCLUDES)
ENDIF(QT4_FOUND)
