IF(KDE4_FOUND)
    SET(profilesgroupssims_AVAILABLE_FRONTENDS kde)
    SET(profilesgroupssims_kde_DEPENDENCY rcoreqt galileiqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(profilesgroupssims_frontend profilesgroupssims kde profilesgroupssims_INCLUDES)
ENDIF(KDE4_FOUND)
