IF(KDE3_FOUND)
    SET(profilesgroupssims_AVAILABLE_FRONTENDS kde)
    SET(profilesgroupssims_kde_DEPENDENCY rcorekde ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(profilesgroupssims_frontend profilesgroupssims kde profilesgroupssims_INCLUDES)
ENDIF(KDE3_FOUND)
