IF(KDE3_FOUND)
    SET(profilesagree_AVAILABLE_FRONTENDS kde)
    SET(profilesagree_kde_DEPENDENCY rcorekde ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(profilesagree_frontend profilesagree kde profilesagree_INCLUDES)
ENDIF(KDE3_FOUND)
