IF(KDE4_FOUND)
    SET(profilesagree_AVAILABLE_FRONTENDS kde)
    SET(profilesagree_kde_DEPENDENCY rcoreqt galileiqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(profilesagree_frontend profilesagree kde profilesagree_INCLUDES)
ENDIF(KDE4_FOUND)
