IF(KDE4_FOUND)
    SET(profilessims_AVAILABLE_FRONTENDS kde)
    SET(profilessims_kde_DEPENDENCY rcorekde galileikde ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(profilessims_frontend profilessims kde profilessims_INCLUDES)
ENDIF(KDE4_FOUND)
