IF(QT4_FOUND)
    SET(nngga_profiles_AVAILABLE_FRONTENDS qt)
    SET(nngga_profiles_qt_DEPENDENCY rcoreqt ${QT_LIBRARIES})
    ADD_FRONTEND_SOURCE_FILE(nngga_profiles_frontend nngga_profiles qt nngga_profiles_INCLUDES)
ENDIF(QT4_FOUND)
