IF(KDE4_FOUND)
    SET(logentropy_AVAILABLE_FRONTENDS kde)
    SET(logentropy_kde_DEPENDENCY rcoreqt galileiqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(logentropy_frontend logentropy kde logentropy_INCLUDES)
ENDIF(KDE4_FOUND)
