IF(QT4_FOUND)
    SET(metaenginesum_AVAILABLE_FRONTENDS qt)
    SET(metaenginesum_qt_DEPENDENCY rcoreqt ${QT_LIBRARIES})
    ADD_FRONTEND_SOURCE_FILE(metaenginesum_frontend metaenginesum qt metaenginesum_INCLUDES)
ENDIF(QT4_FOUND)
