IF(KDE3_FOUND)
    SET(langen_AVAILABLE_FRONTENDS kde)
    SET(langen_kde_DEPENDENCY rcorekde ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(langen_frontend langen kde langen_INCLUDES)
ENDIF(KDE3_FOUND)
