IF(KDE3_FOUND)
    SET(gravitation_community_AVAILABLE_FRONTENDS kde)
    SET(gravitation_community_kde_DEPENDENCY rcorekde ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(gravitation_community_frontend gravitation_community kde gravitation_community_INCLUDES)
ENDIF(KDE3_FOUND)
