IF(KDE4_FOUND)
    SET(gravitation_community_AVAILABLE_FRONTENDS kde)
    SET(gravitation_community_kde_DEPENDENCY rcoreqt ${KDE4_KDEUI_LIBS} ${KDE4_KIO_LIBS})
    ADD_FRONTEND_SOURCE_FILE(gravitation_community_frontend gravitation_community kde gravitation_community_INCLUDES)
ENDIF(KDE4_FOUND)
