IF(KDE3_FOUND)
    SET(langpt_AVAILABLE_FRONTENDS kde)
    SET(langpt_kde_DEPENDENCY rcorekde ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(langpt_frontend langpt kde langpt_INCLUDES)
ENDIF(KDE3_FOUND)
